name: Build and Deploy Astro

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: self-hosted
    name: Build and Deploy on LAN
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Astro Check
        run: pnpm astro check

      - name: Build Astro
        run: pnpm astro build

      - name: Deploy to /var/www
        run: |
          echo "Deploying on kong@wyse5070"
          rsync -av --delete ./dist/ /var/www/boardbon.tinymeepletalk.com/
          echo "Deployment finished on kong@wyse5070"
