# .github/workflows/deploy.yml
name: Deploy to Kong's Directory

on:
  push:
    branches: [ main ]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to boardbon.tinymeepletalk.com
    
    steps:
    - name: Deploy via Cloudflare SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}  # deploy user
        key: ${{ secrets.SSH_KEY }}  # SSH key for deploy user
        port: ${{ secrets.PORT }}
        timeout: 60s
        command_timeout: 15m
        script: |
          echo "🚀 GitHub Actions triggered deployment"
          echo "Repository: ${{ github.repository }}"
          echo "Commit: ${{ github.sha }}"
          echo "Triggered by: ${{ github.actor }}"
