name: Deploy Astro to Boardbon

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 2a: Checkout code
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2b: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 2c: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 2d: Build Astro
      - name: Build Astro
        run: pnpm run build

      # Step 2e: Deploy via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: boardbon-ssh.tinymeepletalk.com
          username: kong
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          port: 22
          script: |
            echo "Deploying on host"
            mkdir -p /var/www/boardbon.tinymeepletalk.com
            rsync -avz --delete ./dist/ /var/www/boardbon.tinymeepletalk.com/
            echo "Deployment finished on host"
